(() => {
  'use strict';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  let firstSetup=false, authed=false, companies=[], activeSelect=null;
  const SESSION='AHMADI_ADMIN_ACTIVE_V2';
  const ADMIN_ACCESS='78789852';
  const COMPANY_CACHE='AHMADI_ADMIN_COMPANIES_CACHE_V1';
  const svg={check:'<path d="m5 12 4 4L19 6"/>',copy:'<rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/>',edit:'<path d="M12 20h9"/><path d="M16.5 3.5a2.1 2.1 0 0 1 3 3L8 18l-4 1 1-4Z"/>',trash:'<path d="M3 6h18M8 6V4h8v2M6 6l1 15h10l1-15"/>',pause:'<path d="M8 5v14M16 5v14"/>',play:'<path d="m8 5 11 7-11 7Z"/>',key:'<circle cx="8" cy="15" r="4"/><path d="m11 12 9-9M17 6l3 3M14 9l3 3"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>'};
  const icon=(n,size=16)=>`<svg viewBox="0 0 24 24" width="${size}" height="${size}" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${svg[n]||svg.key}</svg>`;
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const fmt=ms=>ms?new Intl.DateTimeFormat('ar',{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(Number(ms))):'غير محدد';
  function toast(msg,type='success'){const root=$('#adminToast'),el=document.createElement('div');el.className=`admin-toast ${type}`;el.textContent=msg;root.replaceChildren(el);requestAnimationFrame(()=>el.classList.add('show'));setTimeout(()=>{el.classList.remove('show');setTimeout(()=>el.remove(),220)},3200)}
  function field(label,id,type='text',value='',placeholder='',hint='',attrs=''){return `<div class="a-field"><label for="${id}">${label}</label><input id="${id}" type="${type}" value="${esc(value)}" placeholder="${esc(placeholder)}" ${attrs}>${hint?`<small>${hint}</small>`:''}</div>`}
  function selectField(label,id,opts,value='',hint=''){return `<div class="a-field"><label for="${id}">${label}</label><select id="${id}">${opts.map(o=>`<option value="${esc(o[0])}" ${String(o[0])===String(value)?'selected':''}>${esc(o[1])}</option>`).join('')}</select>${hint?`<small>${hint}</small>`:''}</div>`}
  function openModal(title,body,foot=''){ $('#adminModal').innerHTML=`<div class="admin-modal-overlay"><div class="admin-modal"><div class="admin-modal-head"><h3>${title}</h3><button class="admin-close" type="button" data-close>×</button></div><div class="admin-modal-body">${body}</div>${foot?`<div class="admin-modal-foot">${foot}</div>`:''}</div></div>`;enhanceSelects($('#adminModal'));$$('[data-close]',$('#adminModal')).forEach(b=>b.onclick=closeModal);$('#adminModal .admin-modal-overlay').addEventListener('click',e=>{if(e.target===e.currentTarget)closeModal()});}
  function closeModal(){closeSelect();$('#adminModal').innerHTML=''}
  function durationExpiry(value,unit,base=Date.now()){
    if(unit==='unlimited')return null;const n=Math.max(1,Number(value)||1),d=new Date(base);
    if(unit==='hours')d.setHours(d.getHours()+n);if(unit==='days')d.setDate(d.getDate()+n);if(unit==='weeks')d.setDate(d.getDate()+n*7);if(unit==='months')d.setMonth(d.getMonth()+n);if(unit==='years')d.setFullYear(d.getFullYear()+n);return d.getTime();
  }
  function remaining(row){if(!row.expires_at)return 'غير محدد';const diff=Number(row.expires_at)-Date.now();if(diff<=0)return 'منتهي';const days=Math.ceil(diff/86400000);if(days>365)return `${Math.ceil(days/365)} سنة`;if(days>30)return `${Math.ceil(days/30)} شهر`;if(days>7)return `${Math.ceil(days/7)} أسبوع`;return `${days} يوم`;}
  function statusOf(row){if(row.expires_at&&Date.now()>Number(row.expires_at))return ['منتهي','expired'];if(row.status!=='active')return ['موقوف','inactive'];return ['فعال',''];}

  function cachedCompanies(){try{const v=JSON.parse(localStorage.getItem(COMPANY_CACHE)||'[]');return Array.isArray(v)?v:[]}catch(_){return []}}
  function cacheCompanies(list){try{localStorage.setItem(COMPANY_CACHE,JSON.stringify(Array.isArray(list)?list:[]))}catch(_){}}
  function applyStats(list){const now=Date.now(),total=list.length,active=list.filter(r=>r.status==='active'&&(!r.expires_at||Number(r.expires_at)>=now)).length,expired=list.filter(r=>r.expires_at&&Number(r.expires_at)<now).length;$('#statTotal').textContent=total;$('#statActive').textContent=active;$('#statExpired').textContent=expired;}
  function friendlyError(error){const m=String(error?.message||'');if(/fetch|network|failed|http|timeout|مهلة|الخادم|الاتصال/i.test(m))return 'تعذر الوصول إلى خدمة البيانات الآن. يمكنك متابعة استخدام لوحة الإدارة، وسيعاد الاتصال عند توفر الإنترنت.';return m||'تعذر تنفيذ العملية.';}

  function detectState(){
    $('#adminConnectionText').textContent=navigator.onLine===false?'وضع بدون إنترنت':'لوحة الإدارة جاهزة';
    if(sessionStorage.getItem(SESSION)==='1'){authed=true;showApp();}
  }

  async function authSubmit(e){
    e.preventDefault();
    const key=$('#adminKey').value.trim(),btn=$('#adminSubmit'),old=btn.textContent;
    btn.disabled=true;btn.textContent='جارٍ الدخول...';
    try{
      if(key!==ADMIN_ACCESS)throw new Error('مفتاح دخول الإدارة غير صحيح.');
      authed=true;sessionStorage.setItem(SESSION,'1');showApp();toast('تم فتح لوحة الإدارة.');
    }catch(err){toast(err.message||'تعذر الدخول','error')}finally{btn.disabled=false;btn.textContent=old}
  }
  function showApp(){$('#adminAuth').classList.add('hidden');$('#adminApp').classList.remove('hidden');refreshAll()}
  async function refreshAll(){
    if(!authed)return;
    const q=$('#companySearch')?.value||'';
    if(navigator.onLine===false){
      const all=cachedCompanies();companies=q?all.filter(r=>[r.company_key,r.company_name,r.owner_name].some(v=>String(v||'').toLowerCase().includes(q.toLowerCase()))):all;applyStats(all);renderCompanies();$('#adminConnectionText').textContent='وضع بدون إنترنت';return;
    }
    try{
      const [list,stats]=await Promise.all([AhmadiCloud.listCompanies(q),AhmadiCloud.companyStats()]);companies=list;if(!q)cacheCompanies(list);$('#statTotal').textContent=stats.total||0;$('#statActive').textContent=stats.active||0;$('#statExpired').textContent=stats.expired||0;renderCompanies();$('#adminConnectionText').textContent='لوحة الإدارة جاهزة';
    }catch(e){
      const all=cachedCompanies();companies=q?all.filter(r=>[r.company_key,r.company_name,r.owner_name].some(v=>String(v||'').toLowerCase().includes(q.toLowerCase()))):all;applyStats(all);renderCompanies();$('#adminConnectionText').textContent='تعذر التحديث الآن';toast(friendlyError(e),'error');
    }
  }
  function renderCompanies(){const root=$('#companyList');root.innerHTML=companies.length?companies.map(row=>{const [st,cls]=statusOf(row);return `<article class="company-card"><div class="company-head"><span class="company-badge">${icon('key',22)}</span><div><strong>${esc(row.company_name||'شركة بدون اسم')}</strong><small>${esc(row.owner_name||'بدون اسم مالك')}</small></div><span class="status-pill ${cls}">${st}</span></div><div class="company-key-box"><span>مفتاح الشركة</span><b>${esc(row.company_key)}</b></div><div class="company-meta"><span><small>انتهاء الصلاحية</small><b>${row.expires_at?fmt(row.expires_at):'بدون انتهاء'}</b></span><span><small>المدة المتبقية</small><b>${remaining(row)}</b></span><span><small>آخر تحديث</small><b>${fmt(row.updated_at)}</b></span><span><small>مجموعات البيانات</small><b>${Number(row.dataset_count||0)}</b></span></div><div class="company-actions"><button class="primary" data-copy="${esc(row.company_key)}">${icon('copy')} نسخ المفتاح</button><button data-edit="${row.id}">${icon('edit')} تعديل / تمديد</button><button data-toggle="${row.id}" data-status="${row.status}">${icon(row.status==='active'?'pause':'play')} ${row.status==='active'?'إيقاف':'تفعيل'}</button><button class="danger" data-delete="${row.id}">${icon('trash')} حذف</button></div></article>`}).join(''):`<div class="admin-empty"><strong>لا توجد مفاتيح مطابقة</strong><p>أضف مفتاح شركة جديد أو غيّر كلمة البحث.</p></div>`}

  function openAdd(){openModal('إضافة مفتاح شركة',`<div class="admin-form-grid">${field('اسم الشركة','newCompanyName','text','','مثال: شركة أحمد','يظهر في لوحة الإدارة.')}${field('اسم صاحب الحساب','newOwnerName','text','','مثال: م. أحمد معمر','اسم صاحب المفتاح.')}${field('مفتاح الشركة','newCompanyKey','text','','مثال: AHM-2401','يستخدم في تسجيل الدخول.','required')}${field('كلمة المرور','newCompanyPassword','text','','كلمة مرور الشركة','4 خانات على الأقل.','required')}${field('مدة الاشتراك','newDuration','number','30','30','الرقم ثم اختر الوحدة.','min="1" step="1"')}${selectField('وحدة المدة','newDurationUnit',[['hours','ساعة'],['days','يوم'],['weeks','أسبوع'],['months','شهر'],['years','سنة'],['unlimited','بدون انتهاء']],'days','يتم حساب الانتهاء من لحظة الحفظ.')}</div>`,`<button class="admin-secondary" data-generate type="button">توليد مفتاح</button><button class="admin-secondary" data-close type="button">إلغاء</button><button class="admin-primary" data-save-new type="button">حفظ المفتاح</button>`);$('#adminModal [data-generate]').onclick=()=>{$('#newCompanyKey').value='AHM-'+Math.random().toString(36).slice(2,8).toUpperCase()};$('#adminModal [data-save-new]').onclick=saveNew;}
  async function saveNew(){try{const unit=$('#newDurationUnit').value,expiresAt=durationExpiry($('#newDuration').value,unit);await AhmadiCloud.createCompany({companyName:$('#newCompanyName').value.trim(),ownerName:$('#newOwnerName').value.trim(),companyKey:$('#newCompanyKey').value.trim(),password:$('#newCompanyPassword').value,expiresAt});closeModal();toast('تم إنشاء مفتاح الشركة.');refreshAll()}catch(e){toast(friendlyError(e),'error')}}
  function openEdit(id){const r=companies.find(x=>x.id===id);if(!r)return;openModal('تعديل مفتاح الشركة',`<div class="admin-form-grid">${field('اسم الشركة','editCompanyName','text',r.company_name||'','','')}${field('اسم صاحب الحساب','editOwnerName','text',r.owner_name||'','','')}${field('مفتاح الشركة','editCompanyKey','text',r.company_key||'','','')}${field('كلمة مرور جديدة','editCompanyPassword','password','','اتركها فارغة بدون تغيير','')}${field('مدة إضافية','editDuration','number','30','30','تحسب من تاريخ الانتهاء الحالي إن كان ما زال فعالاً.','min="1" step="1"')}${selectField('وحدة المدة','editDurationUnit',[['hours','ساعة'],['days','يوم'],['weeks','أسبوع'],['months','شهر'],['years','سنة'],['unlimited','إلغاء تاريخ الانتهاء']],'days','')}</div>`,`<button class="admin-secondary" data-close type="button">إلغاء</button><button class="admin-primary" data-save-edit type="button">حفظ التعديلات</button>`);$('#adminModal [data-save-edit]').onclick=()=>saveEdit(r);}
  async function saveEdit(r){try{const unit=$('#editDurationUnit').value,base=Math.max(Date.now(),Number(r.expires_at||0)),expiresAt=unit==='unlimited'?null:durationExpiry($('#editDuration').value,unit,base);await AhmadiCloud.updateCompany(r.id,{companyName:$('#editCompanyName').value.trim(),ownerName:$('#editOwnerName').value.trim(),companyKey:$('#editCompanyKey').value.trim(),password:$('#editCompanyPassword').value||'',expiresAt});closeModal();toast('تم تحديث بيانات المفتاح.');refreshAll()}catch(e){toast(friendlyError(e),'error')}}
  async function toggle(id,status){try{await AhmadiCloud.updateCompany(id,{status:status==='active'?'inactive':'active'});toast(status==='active'?'تم إيقاف المفتاح.':'تم تفعيل المفتاح.');refreshAll()}catch(e){toast(friendlyError(e),'error')}}
  function askDelete(id){const r=companies.find(x=>x.id===id);if(!r)return;openModal('حذف مفتاح الشركة',`<div style="padding:8px 2px;line-height:1.9;font-size:11px;color:#677780">سيتم حذف المفتاح <b>${esc(r.company_key)}</b> وجميع بيانات المزامنة المرتبطة به. هذا الإجراء لا يمكن التراجع عنه.</div>`,`<button class="admin-secondary" data-close type="button">إلغاء</button><button class="admin-danger" data-confirm-delete type="button">حذف نهائي</button>`);$('#adminModal [data-confirm-delete]').onclick=async()=>{try{await AhmadiCloud.deleteCompany(id);closeModal();toast('تم حذف المفتاح وبياناته.');refreshAll()}catch(e){toast(friendlyError(e),'error')}}}
  async function copyText(text){try{await navigator.clipboard.writeText(text);toast('تم نسخ مفتاح الشركة.')}catch(_){const t=document.createElement('textarea');t.value=text;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove();toast('تم نسخ مفتاح الشركة.')}}

  function enhanceSelects(root=document){root.querySelectorAll('select:not(.admin-select-ready)').forEach(select=>{select.classList.add('admin-select-ready','admin-select-hidden');const b=document.createElement('button');b.type='button';b.className='admin-select-trigger';b.innerHTML='<span></span><span>⌄</span>';select.insertAdjacentElement('afterend',b);const sync=()=>b.firstElementChild.textContent=select.options[select.selectedIndex]?.textContent||'اختر';sync();select.addEventListener('change',sync);b.onclick=()=>openSelect(select,b)})}
  function openSelect(select,trigger){closeSelect();const back=document.createElement('div'),pop=document.createElement('div');back.className='admin-select-backdrop';pop.className='admin-select-popover';pop.innerHTML=`<div class="admin-select-search">${icon('search')}<input type="search" placeholder="ابحث داخل القائمة..."></div><div class="admin-select-options"></div>`;document.body.append(back,pop);activeSelect={back,pop};const input=$('input',pop),host=$('.admin-select-options',pop),opts=[...select.options];const draw=()=>{const q=input.value.trim().toLowerCase();host.innerHTML=opts.map((o,i)=>({o,i})).filter(x=>!q||x.o.textContent.toLowerCase().includes(q)).map(x=>`<button type="button" class="admin-select-option ${x.o.selected?'selected':''}" data-i="${x.i}"><span>${esc(x.o.textContent)}</span><span>${x.o.selected?'✓':''}</span></button>`).join('')};draw();host.onclick=e=>{const b=e.target.closest('[data-i]');if(!b)return;select.selectedIndex=Number(b.dataset.i);select.dispatchEvent(new Event('change',{bubbles:true}));closeSelect()};input.oninput=draw;back.onclick=closeSelect;const r=trigger.getBoundingClientRect(),w=Math.min(Math.max(180,r.width),Math.min(360,innerWidth-18));pop.style.width=w+'px';pop.style.left=Math.max(9,Math.min(r.right-w,innerWidth-w-9))+'px';requestAnimationFrame(()=>{const h=Math.min(pop.scrollHeight,360),top=(r.bottom+6+h<innerHeight-9)?r.bottom+6:Math.max(9,r.top-h-6);pop.style.top=top+'px';input.focus({preventScroll:true})})}
  function closeSelect(){activeSelect?.back?.remove();activeSelect?.pop?.remove();activeSelect=null}

  $('#adminLoginForm').addEventListener('submit',authSubmit);$('#adminRefresh').addEventListener('click',refreshAll);$('#addCompanyBtn').addEventListener('click',openAdd);$('#companySearch').addEventListener('input',()=>{clearTimeout(refreshAll.t);refreshAll.t=setTimeout(refreshAll,180)});$('#adminLogout').addEventListener('click',()=>{sessionStorage.removeItem(SESSION);location.reload()});$('#companyList').addEventListener('click',e=>{const copy=e.target.closest('[data-copy]'),edit=e.target.closest('[data-edit]'),toggleBtn=e.target.closest('[data-toggle]'),del=e.target.closest('[data-delete]');if(copy)return copyText(copy.dataset.copy);if(edit)return openEdit(edit.dataset.edit);if(toggleBtn)return toggle(toggleBtn.dataset.toggle,toggleBtn.dataset.status);if(del)return askDelete(del.dataset.delete)});
  window.addEventListener('online',()=>{$('#adminConnectionText')&&($('#adminConnectionText').textContent='جارٍ تحديث البيانات...');if(authed)refreshAll()});
  window.addEventListener('offline',()=>{$('#adminConnectionText')&&($('#adminConnectionText').textContent='وضع بدون إنترنت');if(authed)refreshAll()});
  detectState();
})();
