const CACHE='ahmadi-electric-v13.12';
const NOTIFY_CACHE='ahmadi-electric-notify-state-v1';
const SNAPSHOT_KEY='./__ahmadi_notification_snapshot__';
const FILES=['./','./index.html','./styles.css','./app.js','./turso-config.js','./turso-sync.js','./admin.html','./admin.css','./admin.js','./manifest.webmanifest','./logo.jpg','./icon-192.png','./icon-512.png'];
self.addEventListener('install',e=>{e.waitUntil(caches.open(CACHE).then(c=>c.addAll(FILES)).then(()=>self.skipWaiting()));});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE&&k!==NOTIFY_CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()));});
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;e.respondWith(fetch(e.request).then(r=>{const copy=r.clone();caches.open(CACHE).then(c=>c.put(e.request,copy)).catch(()=>{});return r;}).catch(()=>caches.match(e.request).then(r=>r||caches.match('./index.html'))));});
self.addEventListener('notificationclick',event=>{event.notification.close();event.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(list=>{for(const client of list){if('focus'in client)return client.focus();}if(clients.openWindow)return clients.openWindow('./');}));});
self.addEventListener('message',event=>{if(event.data?.type!=='AHMADI_NOTIFICATION_SNAPSHOT')return;const payload=event.data.payload||{};event.waitUntil(caches.open(NOTIFY_CACHE).then(c=>c.put(SNAPSHOT_KEY,new Response(JSON.stringify(payload),{headers:{'content-type':'application/json'}}))));});
async function readNotificationSnapshot(){try{const c=await caches.open(NOTIFY_CACHE),r=await c.match(SNAPSHOT_KEY);return r?await r.json():null;}catch(_){return null;}}
self.addEventListener('periodicsync',event=>{if(event.tag!=='ahmadi-daily-check')return;event.waitUntil((async()=>{const s=await readNotificationSnapshot();if(!s?.enabled)return;if(s.debtorsEnabled&&s.debtors?.count){await self.registration.showNotification('المشتركون المستحق عليهم',{body:`${s.debtors.count} مشترك • إجمالي المستحق ₪ ${Number(s.debtors.total||0).toFixed(2)}${s.debtors.names?' • '+s.debtors.names:''}`,icon:'icon-192.png',badge:'icon-192.png',tag:'ahmadi-daily-debtors',dir:'rtl',lang:'ar'});}if(s.expiryEnabled&&s.expiry?.count){await self.registration.showNotification('اشتراكات على وشك الانتهاء',{body:`${s.expiry.count} اشتراك خلال ${s.expiry.days||7} يوم${s.expiry.names?' • '+s.expiry.names:''}`,icon:'icon-192.png',badge:'icon-192.png',tag:'ahmadi-daily-expiry',dir:'rtl',lang:'ar'});}})());});
